version: "3.9"
services:
  serverless_deployment:
    build: .
    volumes:
      - ./build:/app
      - ~/.aws/credentials:/root/.aws/credentials
    working_dir: /app
    command: >
      sh -c "npm install && serverless deploy --stage dev --region us-east-1"