service: cf-image-resizing
frameworkVersion: '2'
configValidationMode: 'off'
plugins:
  - '@silvermine/serverless-plugin-cloudfront-lambda-edge'
provider:
  stage: dev
  region: ap-southeast-1
  name: aws
  runtime: nodejs12.x
  versionFunctions: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource:
        - arn:aws:lambda:*:*:function:ResizeImage
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource:
        - arn:aws:s3:::demo-cf-image-resize/*
    - Effect: Allow
      Action:
        - logs:CreateLogStream
        - logs:CreateLogGroup
        - logs:PutLogEvents
      Resource:
        - arn:aws:logs:*:*:log-group:/aws/lambda/*
functions:
  ResizeImage:
    name: resizeImage
    handler: src/handlers.originResponse
#    lambdaAtEdge:
#      distribution: 'ENSEIQTTLYA8C'
#      eventType: 'viewer-request'
#      pathPattern: 'photos/*.jpg'
